Converted t maven archtype + added lombok in entity class + Polymorph…
Maitri-Shah24/Tic-Tac-Toe- pull request #1
Opened 2024-09-10 05:35 UTC by Maitri-Shah24

…ism achieved

2024-09-11 11:26 UTC, NisargPipaliya requested changes

2024-09-11 11:26 UTC, NisargPipaliya commented on src/main/java/com/example/HumanPlayer.java
> +        while (board.isPositionTaken(pos))
Can go for do while loop

2024-09-11 11:26 UTC, NisargPipaliya commented on src/main/java/com/example/HumanPlayer.java
> +        int pos = scanner.nextInt();
Check the case where user is not entering numbers.
Or number greater than 9 or less than 1

2024-09-11 11:26 UTC, NisargPipaliya commented on src/main/java/com/example/Board.java
In Is Position Taken Function,
Instead of comparing it with two symbols and calling contains function, just directly compare it with empty char, it would be less costly.

2024-09-11 11:26 UTC, NisargPipaliya commented on src/main/java/com/example/Board.java
in `checkWinner` condition, should remove `playerPosition` array, it is just occupying extra space and need to manage it,
just check the board for winning condition as it would occupy less space and would take around same time.

2024-09-11 11:26 UTC, NisargPipaliya commented on src/main/java/com/example/Board.java
in `checkWinner`, execute the `if` condition for checking tie before preparing list and executing for loop.

2024-09-11 11:26 UTC, NisargPipaliya commented on src/main/java/com/example/CpuPlayer.java
> +@Getter
Add this annotations in parent class, no need to mention it twice and in all child class, if child is not having any extra field that is suppose to be exposed.
like here `Random` does not need a getter and setter.

2024-09-11 11:26 UTC, NisargPipaliya commented on src/main/java/com/example/Game.java
> +        return scanner.nextLine().equalsIgnoreCase("Y");
Check for the case where user enters something other than `Y` or `N`

2024-09-12 04:27 UTC, shreya6323 commented on src/main/java/com/example/Game.java
> +        return scanner.nextLine().equalsIgnoreCase("Y");
Try to close the scanner object when the user quits the game

2024-09-12 04:27 UTC, shreya6323 commented on src/main/java/com/example/Game.java
> +        if(player.equals(player1))
Can pass the name to the printBoard Method to avoid redundant print statements

2024-09-12 04:27 UTC, shreya6323 commented on src/main/java/com/example/Game.java
> +        return checkWinner(player.getName());
Call checkWinner() only after some iterations

2024-09-12 04:27 UTC, shreya6323 commented on src/main/java/com/example/Board.java
Rather than statically checking the position using switch case , try to go for function which does the conversion of the position.

2024-09-12 08:51 UTC, Maitri-Shah24 commented
Did all the changes in newer commits

2024-09-12 08:51 UTC, merged