Some modifications
Maitri-Shah24/Tic-Tac-Toe- pull request #2
Opened 2024-09-12 16:39 UTC by Maitri-Shah24

Modified all the previous comment given by Ayan bhai, Nisarg and Shreya.

2024-09-14 18:59 UTC, Maitri-Shah24 commented
Please try to review full code and only loaded differences

2024-09-15 04:25 UTC, shreya6323 commented
> Please try to review full code and not only loaded differences

Can you also check the review I have mentioned in your previous commit of this branch

2024-09-15 05:25 UTC, shreya6323 commented on src/main/java/com/example/Board.java
>                  return "Computer wins! Sorry (\u2060 \u2060⚈̥\u2060⌢\u2060⚈̥\u2060)" + playerName;
Avoid repeating the print statement related to winner

2024-09-15 05:25 UTC, shreya6323 commented on src/main/java/com/example/Board.java
in reset() declare 2 as constant

2024-09-15 05:25 UTC, shreya6323 commented on src/main/java/com/example/Game.java
> +        System.out.println("Enter the grid size: (3 for 3x3, 4 for 4x4 etc)");
Avoid using print statements in Constructor

2024-09-15 05:25 UTC, shreya6323 commented on src/main/java/com/example/Game.java
Try to modularize the things in constructor. It is preferred to have only initialization things over there

2024-09-15 05:25 UTC, shreya6323 commented on src/main/java/com/example/Game.java
According to Tic-Tac-Toe ruleset, the one with 'X' will get the first chance, so try to incorporate that logic in the code.

2024-09-15 06:36 UTC, NisargPipaliya requested changes

2024-09-15 06:36 UTC, NisargPipaliya commented on src/main/java/com/example/HumanPlayer.java
Update the print statements according to board size.

2024-09-15 06:36 UTC, NisargPipaliya commented on src/main/java/com/example/HumanPlayer.java
The way of checking vaild input is not that efficient, i.e. need to create exception object, throw it, catch it, print message.
Instead assume user provides invalid input, and validate it before using it.

2024-09-15 11:51 UTC, Maitri-Shah24 commented
> > Please try to review full code and not only loaded differences
> > Also check the comment I have mentioned in your previous commit of this branch.
Done

2024-09-15 12:13 UTC, Maitri-Shah24 commented on src/main/java/com/example/HumanPlayer.java
Done

2024-09-15 12:13 UTC, Maitri-Shah24 commented on src/main/java/com/example/Game.java
> +        System.out.println("Enter the grid size: (3 for 3x3, 4 for 4x4 etc)");
This Game constructor rn is used to create instance in TicTacToe class if I don't print statements here then would have to call all the methods in TicTacToe class with instance of Game class which would make a mess. Would take care next time.

2024-09-15 12:14 UTC, Maitri-Shah24 commented on src/main/java/com/example/Board.java
That 2 is never going to change as it is the denoting separators, intersection symbols for printing board. So I think there is no use to declare it as a constant bcz the method for printing board is not going to change.

2024-09-15 12:14 UTC, Maitri-Shah24 commented on src/main/java/com/example/Board.java
>                  return "Computer wins! Sorry (\u2060 \u2060⚈̥\u2060⌢\u2060⚈̥\u2060)" + playerName;
Done

2024-09-15 12:25 UTC, NisargPipaliya approved these changes

2024-09-16 02:17 UTC, shreya6323 approved these changes
Approved !

2024-09-16 05:37 UTC, merged